- name: Install and configure GLPI Agent on Ubuntu machines
  hosts: all
  become: yes
  tasks:
    - name: Ensure wget is installed
      ansible.builtin.package:
        name: wget
        state: present

    - name: Download the GLPI agent AppImage
      ansible.builtin.get_url:
        url: https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-x86_64.AppImage
        dest: /tmp/glpi-agent-1.11-x86_64.AppImage
        mode: '0755'

    - name: Verify the GLPI agent AppImage exists
      ansible.builtin.stat:
        path: /tmp/glpi-agent-1.11-x86_64.AppImage
      register: glpi_agent_file

    - name: Fail if the GLPI agent AppImage is missing
      ansible.builtin.fail:
        msg: "The GLPI agent AppImage file was not downloaded."
      when: not glpi_agent_file.stat.exists

    - name: Install the GLPI agent (with sudo)
      ansible.builtin.shell:
        cmd: sudo ./glpi-agent-1.11-x86_64.AppImage --install --server https://infra.beehyv.com
        chdir: /tmp

    - name: Start the GLPI agent
      ansible.builtin.shell:
        cmd: sudo glpi-agent

    - name: Ensure GLPI agent starts on boot
      ansible.builtin.systemd:
        name: glpi-agent
        enabled: yes
        state: started
