- name: Install and configure GLPI Agent on Ubuntu machines
  hosts: all
  become: yes
  tasks:
    - name: Download the GLPI agent AppImage using wget
      ansible.builtin.command:
        cmd: wget https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-x86_64.AppImage -O /tmp/glpi-agent-1.11-x86_64.AppImage

    - name: Check file existence after download
      ansible.builtin.command:
        cmd: ls -l /tmp/glpi-agent-1.11-x86_64.AppImage

    - name: Make the GLPI agent AppImage executable
      ansible.builtin.file:
        path: /tmp/glpi-agent-1.11-x86_64.AppImage
        mode: '0755'

    - name: Install the GLPI agent
      ansible.builtin.command:
        cmd: ./glpi-agent-1.11-x86_64.AppImage --install --server https://infra.beehyv.com
        chdir: /tmp
      become: yes

    - name: Start the GLPI agent
      ansible.builtin.command:
        cmd: glpi-agent
      become: yes
