---
- name: Setup and run GLPI Agent
  hosts: all
  become: true  # Ensure that the playbook runs with sudo privileges
  tasks:
    - name: Download GLPI agent AppImage
      get_url:
        url: https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-x86_64.AppImage
        dest: /tmp/glpi-agent-1.11-x86_64.AppImage
        mode: '0755'  # Set the file permissions to be executable upon download

    - name: Make GLPI agent AppImage executable
      file:
        path: /tmp/glpi-agent-1.11-x86_64.AppImage
        mode: '0755'  # Ensure the file is executable

    - name: Install GLPI agent
      command: /tmp/glpi-agent-1.11-x86_64.AppImage --install --server https://infra.beehyv.com
      become: true  # Ensure the installation step runs as root
      args:
        creates: /etc/glpi-agent # This assumes the installation creates this file; adjust as needed for your environment

    - name: Run GLPI agent service
      command: glpi-agent
      become: true  # Ensure this runs with root privileges
      args:
        creates: /var/log/glpi-agent.log # Assuming the agent creates a log file here; adjust path as needed
