---
- name: Deploy GLPI Agent Using AppImage
  hosts: all
  become: true
  tasks:
    - name: Download GLPI Agent AppImage
      get_url:
        url: https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-x86_64.AppImage
        dest: /tmp/glpi-agent-1.11-x86_64.AppImage
        mode: '0755'

    - name: Make the AppImage executable
      file:
        path: /tmp/glpi-agent-1.11-x86_64.AppImage
        mode: '0755'

    - name: Install GLPI Agent
      command: >
        /tmp/glpi-agent-1.11-x86_64.AppImage --install --server http://<GLPI-domain>
      become: true
      args:
        creates: /etc/glpi-agent

    - name: Start GLPI Agent
      command: glpi-agent
      become: true
